<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.0.5" />
    <PackageReference Include="System.Management.Automation" Version="7.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDigit.Exceptions\DDigit.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="python\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="python\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>contentFiles\any\any\python\</PackagePath>
    </None>
  </ItemGroup>

</Project>
