<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Daan Kuijper, Bert Degenhart Drenth</Authors>
    <Company>Double Dig IT</Company>
    <Copyright>(C) 2026 Double Dig IT</Copyright>
    <Description>Contains the Scripting Libraries for Double Dig IT Core Libraries.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.0.5" />
    <PackageReference Include="System.Management.Automation" Version="7.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDigit.Exceptions\DDigit.Exceptions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="python\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="python\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>true</Pack>
      <PackagePath>contentFiles\any\any\python\</PackagePath>
    </None>
  </ItemGroup>

</Project>
