<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDigit.Classes\DDigit.Classes.csproj" />
    <ProjectReference Include="..\DDigit.DataProvider\DDigit.DataProvider.csproj" />
    <ProjectReference Include="..\DDigit.MetaData\DDigit.MetaData.csproj" />
    <ProjectReference Include="..\DDigit.Results\DDigit.Results.csproj" />
  </ItemGroup>

</Project>
