<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Daan Kuijper, Bert Degenhart Drenth</Authors>
    <Company>Double Dig IT</Company>
    <Copyright>(C) 2026 Double Dig IT</Copyright>
    <Description>Contains the Record Transactions for Double Dig IT Core Libraries.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDigit.Classes\DDigit.Classes.csproj" />
    <ProjectReference Include="..\DDigit.DataProvider\DDigit.DataProvider.csproj" />
    <ProjectReference Include="..\DDigit.MetaData\DDigit.MetaData.csproj" />
    <ProjectReference Include="..\DDigit.Results\DDigit.Results.csproj" />
  </ItemGroup>

</Project>
