<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Daan Kuijper, Bert Degenhart Drenth</Authors>
    <Company>Double Dig IT</Company>
    <Copyright>(C) 2026 Double Dig IT</Copyright>
    <Description>Contains the Scripting Interface for Double Dig IT Core Libraries.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.PowerShell.Commands.Diagnostics" Version="7.5.4" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Management" Version="7.5.4" />
    <PackageReference Include="Microsoft.PowerShell.Commands.Utility" Version="7.5.4" />
    <PackageReference Include="Microsoft.PowerShell.ConsoleHost" Version="7.5.3" />
    <PackageReference Include="Microsoft.WSMan.Management" Version="7.5.4" />
    <PackageReference Include="System.Management.Automation" Version="7.5.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DDigit.DataProvider\DDigit.DataProvider.csproj" />
  </ItemGroup>
</Project>