<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Daan Kuijper, Bert Degenhart Drenth</Authors>
    <Company>Double Dig IT</Company>
    <Copyright>(C) 2026 Double Dig IT</Copyright>
    <Description>Contains the External Data Sources for Double Dig IT Core Libraries.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDigit.Data\DDigit.Data.csproj" />
  </ItemGroup>

</Project>
